### PR TITLE
[FAL-3383] Implement new video UX flow on new video editor

### PR DESCRIPTION
**Pull request by ChrisChV**
This branch adds all the navigation for the new video editor flow.

Internal Jira task: [FAL-3383](https://tasks.opencraft.com/browse/FAL-3383)

**Testing instructions**

- Use this branch https://github.com/openedx/edx-platform/pull/32024 and this branch https://github.com/openedx/frontend-app-course-authoring/pull/498
- Login on studio with a super user.
- We need to test the flow before to create any video.
- On a course create a unit and create a new video. Verify that it redirects to the video gallery, but after loading, it redirects to the video upload page.
- Go to [Django Admin](http://localhost:18010/admin/edxval/coursevideo/) and create a conection with a video and the Demo course.
    - Edit the duration of the videos.
- On a course create a unit and create a new video. Verify that it redirects to the video gallery.
- Check the cancel button
- Create new video and on the video gallery, select a video and go to the next page.
- Verify that the Video ID and de duration are filled.
- Click on the `Replace video button`.

To test the video upload, you need to configure an S3, but there is an easy way to test this

- Read [this comment](https://github.com/openedx/frontend-lib-content-components/pull/326/files#diff-8c87d7bec267a780f66f8210f786b97cec0d8bdafacc162a220d13343393c286R30)
- Update the [videos_handler](https://github.com/openedx/edx-platform/blob/d622db59b7bfe2e4c11fc11b7cb2d475cfda551b/cms/djangoapps/contentstore/views/videos.py#L188) function on edx-paltform to return overwritten data. You can use this [gist as reference](https://gist.github.com/ChrisChV/e662a5bdb4145a80606295f5b677d5b5)
- Create a video and on the video gallery, click on the upload button.
- Upload any video
- Verify that the Video ID and de duration are filled.

**Author notes**

- The video upload only works with an S3 configuration.
- I added a temporal line to test the video upload without an S3 configuration: [Comment](https://github.com/openedx/frontend-lib-content-components/pull/326/files#diff-8c87d7bec267a780f66f8210f786b97cec0d8bdafacc162a220d13343393c286R30)
- This branch was internal reviewed here: https://github.com/open-craft/frontend-lib-content-components/pull/8#issuecomment-1523827421

**Release notes**

**IMPORTANT**: Delete [this line](https://github.com/openedx/frontend-lib-content-components/pull/326/files#diff-8c87d7bec267a780f66f8210f786b97cec0d8bdafacc162a220d13343393c286R30) before merge

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @ChrisChV!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by ChrisChV** [comment]
@jristau1984 This it's ready for a first review. I will check the `codecov/patch` fail

**Review by giovannicimolin — APPROVED** [review]
Tested on internal PR here: https://github.com/open-craft/frontend-lib-content-components/pull/8#issuecomment-1523827421

:+1:

- [x] I tested this:
1. Tested the new video flows and checked that they are working as expected.
2. UI matches mockups (with nit above).
3. Transcripts are pulled in after selecting a video.
- [x] I read through the code
- [x] I checked for accessibility issues: basic checks on tab navigation.
- [ ] Includes documentation

**Comment by ChrisChV** [comment]
> This it's ready for a first review. I will check the `codecov/patch` fail

Done :+1:

**Review by kenclary — APPROVED** [review]
alright

**Comment by openedx-webhooks** [comment]
@ChrisChV 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-lib-content-components&entry.867055334=https://github.com/openedx/frontend-lib-content-components/pull/326&entry.1484655318=https://github.com/ChrisChV&entry.752974735=2023-05-04+23:22&entry.1917517419=2023-05-18+15:49&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
