### PR TITLE
fix: add rtl support to editor

### PR DESCRIPTION
**Pull request by ihor-romaniuk**
**TL;DR -**

This pull request contains feature of dynamically adaptation to RLT or LTR side direction.

**What changed?**

|  Before |  After |
|---|---|
|  image  |  image |

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @ihor-romaniuk! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by mphilbrick211** [comment]
Hi @ihor-romaniuk! Just flagging that some branch conflicts have popped up.

**Comment by ihor-romaniuk** [comment]
Hi @mphilbrick211! Resolved, thanks.

**Comment by mphilbrick211** [comment]
@openedx/teaching-and-learning this is all set for review!

**Comment by mphilbrick211** [comment]
@openedx/2u-tnl - would someone be able to please review / merge this for us?

**Comment by mphilbrick211** [comment]
Hi @openedx/2u-tnl! Would someone be able to please review / merge this for us? Thanks!

**Review by KristinAoki — APPROVED** [review]

**Pull request merged**
