### PR TITLE
Update codecov and add browserslist config

### PR DESCRIPTION
**Pull request by Mashal-m**
Ticket:
[Use shared @edx/browserslist-config](https://github.com/openedx/frontend-wg/issues/47)
[Migrate from Coveralls to Codecov ](https://github.com/openedx/frontend-wg/issues/9)

- This PR move the coverage to CI according to the new guidelines and [depreciation](https://about.codecov.io/blog/codecov-uploader-deprecation-plan/) plan of codecov 
-  used a [shared configuration](https://github.com/edx/browserslist-config).
This change reduces the resultant asset bundle size.

### CODE REVIEW

**Review by abdullahwaheed — APPROVED** [review]

**Comment by Mashal-m** [comment]
Review Requested [Here](https://twou.slack.com/archives/C04BHDFQMDK/p1674467650937519)

**Review by connorhaugh — APPROVED** [review]
looks good to me! Thanks so much for this!

**Comment by abdullahwaheed** [comment]
@connorhaugh could you please merge it as well, we don't have permissions to merge

**Comment by Mashal-m** [comment]
@connorhaugh conflicts resolved, can you please merge this? :)

**Comment by Mashal-m** [comment]
@connorhaugh conflicts resolved, can you please merge this? :)

**Comment by Mashal-m** [comment]
@connorhaugh conflicts resolved, can you please merge this? :)

**Pull request merged**
