### PR TITLE
feat: Fixed delete for additional video url fields

### PR DESCRIPTION
**Pull request by vladislavkeblysh**
- Fixed delete for additional video url fields

Screenshot 2023-11-05 at 14 38 46

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @vladislavkeblysh! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by mphilbrick211** [comment]
Hi @vladislavkeblysh! Looks like there's a failing check - would you mind taking a look?

**Comment by vladislavkeblysh** [comment]
@mphilbrick211 Fixed

**Comment by mphilbrick211** [comment]
> @mphilbrick211 Fixed

There's still a failing check - let me know if you're having issues clearing it, and I can look into it for you. Thanks!

**Comment by mphilbrick211** [comment]
> > @mphilbrick211 Fixed
> 
> There's still a failing check - let me know if you're having issues clearing it, and I can look into it for you. Thanks!

Friendly ping on this, @vladislavkeblysh!

**Comment by mphilbrick211** [comment]
Hi @vladislavkeblysh! Just checking in to see if you plan to pursue this pull request? If not, we can close for now and reopen at a later time.

**Comment by vladislavkeblysh** [comment]
@mphilbrick211 still in progress, will be fixed soon, ty

**Comment by vladislavkeblysh** [comment]
@mphilbrick211 Fixed

**Comment by mphilbrick211** [comment]
Hi @openedx/2u-tnl! This is ready for review.

**Comment by KristinAoki** [comment]
@vladislavkeblysh in the description can you put a more in depth description of the bug that is being fixed?

**Comment by mphilbrick211** [comment]
> @vladislavkeblysh in the description can you put a more in depth description of the bug that is being fixed?

@vladislavkeblysh - friendly follow-up on this!

**Comment by KristinAoki** [comment]
Hi! Thank you for your contribution to this repo. This repo is being deprecated and all the code is being moved to `frontend-app-course-authoring`. If you would like your work to be included in the transition please resolve outstanding requests for this PR. This PR will automatically close once `frontend-app-course-authoring` PR [#1208](https://github.com/openedx/frontend-app-course-authoring/pull/1208) is merged.

**Comment by bradenmacdonald** [comment]
As mentioned above, we've now moved this code into https://github.com/openedx/frontend-app-course-authoring/ so we'll need you to please re-open this PR against `frontend-app-course-authoring` if you'd like to continue it. Feel free to reach out to me if you aren't sure how to do that using git and I can help (basically: add your local `content-components` repo as a remote in `course-authoring`, then pull the branch and rebase it).

**Comment by openedx-webhooks** [comment]
@vladislavkeblysh Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-lib-content-components&entry.867055334=https://github.com/openedx/frontend-lib-content-components/pull/418&entry.1484655318=https://github.com/vladislavkeblysh&entry.752974735=2023-11-05+12:39&entry.1917517419=2024-08-29+19:12&entry.2133058324=No) so we can improve your experience in the future.

**Comment by mphilbrick211** [comment]
> As mentioned above, we've now moved this code into https://github.com/openedx/frontend-app-course-authoring/ so we'll need you to please re-open this PR against `frontend-app-course-authoring` if you'd like to continue it. Feel free to reach out to me if you aren't sure how to do that using git and I can help (basically: add your local `content-components` repo as a remote in `course-authoring`, then pull the branch and rebase it).

@vladislavkeblysh

**Pull request closed without merging**
