### PR TITLE
feat: updated frontend-build & frontend-platform major versions

### PR DESCRIPTION
**Pull request by BilalQamar95**
**Description**
- Major version upgrades, Updating `frontend-build` to v14 & `frontend-platform` to v8 along with respective edx packages
- Updated `snapshots` for failing tests
- [Adds "prepare" script step to allow building from github](https://github.com/BilalQamar95/frontend-lib-content-components/pull/1#issue-2320347074)

### CODE REVIEW

**Comment by bradenmacdonald** [comment]
Hey, are there any blockers on merging this?

**Comment by BilalQamar95** [comment]
> Hey, are there any blockers on merging this?

@bradenmacdonald no blockers, the PR is ready to be reviewed/merge

**Review by pomegranited — APPROVED** [review]
:+1: Thanks for incorporating that `prepare` change @BilalQamar95 :)

This change is working great for course authoring (https://github.com/openedx/frontend-app-course-authoring/pull/1052), but I can't speak for the other MFEs.

- [x] I tested this by using this branch on https://github.com/openedx/frontend-app-course-authoring/pull/1052
- [x] I read through the code
- [x] I checked for accessibility issues by using my keyboard to navigate during testing.
- [x] <strike>Includes documentation</strike> N/A
- [x] <strike>User-facing strings are extracted for translation</strike> N/A

**Comment by bradenmacdonald** [comment]
@BilalQamar95 Do you think you'll be able to get this PR reviewed+merged this week? We have a few PRs building up that depend on this change, so I'm hoping we can use it ASAP.

**Review by rayzhou-bit — COMMENTED** [review]
I tried testing this on hosted devstack with `frontend-app-course-authoring` and am getting `Module not found: Error: Can't resolve '@openedx/paragon'` errors.

**Comment by BilalQamar95** [comment]
@rayzhou-bit I see that you are testing this on hosted devstack, maybe you can provide more details which can help trace the issue. For now both me and my colleague tested this locally & faced no issues.

**Review by rayzhou-bit — APPROVED** [review]
@BilalQamar95 Looks like something was up with my devstack. I reset my `frontend-app-course-authoring` and `frontend-lib-content-components` repos and was able to do some studio testing. The change looks good to me!

**Comment by BilalQamar95** [comment]
@rayzhou-bit can you please merge this as well? I'm unable to do so since I do not have write access to this repository

**Comment by pomegranited** [comment]
Thank you for merging this @rayzhou-bit @BilalQamar95 !
Could we get a new release created for this repo too?

**Pull request merged**
