### PR TITLE
fix: layout responsive

### PR DESCRIPTION
**Pull request by ihor-romaniuk**
**TL;DR -**

This pull request contains mobile phone adaptation fixes for Problem Editor templates.
Added general rearrangement of pages, indentations, and fixed element deformation during adaptation.

**What changed?**

- Select problem type page

|  Before |  After |
|---|---|
|  image  |  image |

- Select problem type page (advanced problems)

|  Before |  After |
|---|---|
|  image  |  image |

- Inner problem page

|  Before |  After |
|---|---|
|  image  |  image |

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @ihor-romaniuk! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by mphilbrick211** [comment]
Hi @openedx/teaching-and-learning @openedx/2u-tnl! Would someone be able to please review / merge this for us? Thanks!

**Comment by mphilbrick211** [comment]
Hi @openedx/2u-tnl! Would someone be able to please review / merge this for us? Thanks!

**Comment by GlugovGrGlib** [comment]
@KristinAoki would it be possible to check and merge this fix and backport PR from your side? Thank you!

**Comment by mphilbrick211** [comment]
Hi @KristinAoki @GlugovGrGlib - just following up on this!

**Review by KristinAoki — APPROVED** [review]

**Comment by KristinAoki** [comment]
Hi! Thank you for your contribution to this repo. This repo is being deprecated and all the code is being moved to `frontend-app-course-authoring`. If you would like your work to be included in the transition please resolve outstanding requests for this PR. This PR will automatically close once `frontend-app-course-authoring` PR [#1208](https://github.com/openedx/frontend-app-course-authoring/pull/1208) is merged.

**Comment by bradenmacdonald** [comment]
As mentioned above, we've now moved this code into https://github.com/openedx/frontend-app-course-authoring/ so we'll need you to please re-open this PR against `frontend-app-course-authoring` if you'd like to continue it. Feel free to reach out to me if you aren't sure how to do that using git and I can help (basically: add your local `content-components` repo as a remote in `course-authoring`, then pull the branch and rebase it).

**Comment by openedx-webhooks** [comment]
@ihor-romaniuk Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-lib-content-components&entry.867055334=https://github.com/openedx/frontend-lib-content-components/pull/422&entry.1484655318=https://github.com/ihor-romaniuk&entry.752974735=2023-11-23+08:43&entry.1917517419=2024-08-29+19:11&entry.2133058324=No) so we can improve your experience in the future.

**Comment by mphilbrick211** [comment]
@ihor-romaniuk FYI above.

**Pull request closed without merging**
