### PR TITLE
fix: default display of "Show Answer" and "Show reset option"

### LINKED ISSUE #401: The 'Show Answer' option in Advanced settings doesn't affect the 'Show Answer' option for a specific Unit.
### Description:

If the `Show Answer` field has been changed in the Advance settings, then the `Finished` state will still remain on the Editor page.

Advanced Settings:

Editor Page:

But the inscription `Default` is correctly attributed:

If you save without changing anything, the value of the `Show answer` field for the course will be set to `Finished`. And this problem is not only with this field. The same behavior for the `Show reset option` field.

Perhaps the problem is that the state is being used (_frontend-lib-content-components/src/editors/data/redux/problem/reducers.js_):
```
const initialState = {
  rawOLX: '',
  problemType: null,
  question: '',
  answers: [],
  correctAnswerCount: 0,
  groupFeedbackList: [],
  generalFeedback: '',
  additionalAttributes: {},
  defaultSettings: {},
  settings: {
    randomization: null,
    scoring: {
      weight: 1,
      attempts: {
        unlimited: true,
        number: '',
      },
    },
    hints: [],
    timeBetween: 0,
    showAnswer: {
      on: ShowAnswerTypesKeys.FINISHED,
      afterAttempts: 0,
    },
    showResetButton: false,
    solutionExplanation: '',
    tolerance: {
      value: null,
      type: ToleranceTypes.none.type,
    },
  },
};
```

### PR DESCRIPTION
**Pull request by DmytroAlipov**
### Description:

I created the [issue](https://github.com/openedx/frontend-lib-content-components/issues/401).
Hardcoding values for showAnswer and showResetButton in initialState leads to incorrect selection of additional states specified in Advanced settings.

Advanced Settings:

Editor Page:

But the inscription `Default` is correctly attributed:

If you save without changing anything, the value of the `Show answer` field for the course will be set to `Finished`(although the default is “closed”, we didn’t change anything in the selection). And this problem is not only with this field. The same behavior for the `Show reset option` field.

The problem is that the state is being used (_frontend-lib-content-components/src/editors/data/redux/problem/reducers.js_):
```
const initialState = {
  rawOLX: '',
  problemType: null,
  question: '',
  answers: [],
  correctAnswerCount: 0,
  groupFeedbackList: [],
  generalFeedback: '',
  additionalAttributes: {},
  defaultSettings: {},
  settings: {
    randomization: null,
    scoring: {
      weight: 1,
      attempts: {
        unlimited: true,
        number: '',
      },
    },
    hints: [],
    timeBetween: 0,
    showAnswer: {
      on: ShowAnswerTypesKeys.FINISHED,
      afterAttempts: 0,
    },
    showResetButton: false,
    solutionExplanation: '',
    tolerance: {
      value: null,
      type: ToleranceTypes.none.type,
    },
  },
};
```

For `Show reset option`:

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @DmytroAlipov!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by e0d** [comment]
@DmytroAlipov seeing some linting failures.

**Comment by DmytroAlipov** [comment]
@e0d I have fixed the linting issues. Although my changes only addressed one error, the other errors were related to the code written before me. It's strange that the checks passed previously.

**Comment by mphilbrick211** [comment]
Hi @openedx/teaching-and-learning! This is ready for review :)

**Review by KristinAoki — APPROVED** [review]

**Comment by KristinAoki** [comment]
@DmytroAlipov Can you resolve the branch conflicts so I can merge the PR?

**Comment by DmytroAlipov** [comment]
@KristinAoki done 😉

**Pull request merged**
