### PR TITLE
fix: resolve  #360 make style consistent across outlines

### LINKED ISSUE #360: Text in headline 2 will always show in capital letter
Text in headline level 2  will always capital letter It's beleived this due to an CSS property that is setted in https://github.com/openedx/frontend-lib-content-components/blob/f942ef95940b2837aea68f570b349ed3aa95e18e/src/editors/data/constants/tinyMCEStyles.js#L132 As when checking the development tools

Here is a screenshot 
image

### PR DESCRIPTION
**Pull request by ghassanmas**
This changes make the style consistent across the first three
 headline line levels

 1. The first level add CSS prop initial
 2. The second level change prop from capital to inital as describted in #360 
 3. No change

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @ghassanmas!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by mphilbrick211** [comment]
Hi @openedx/teaching-and-learning! Would someone be able to review/merge this for us? Thanks!

**Comment by mphilbrick211** [comment]
> Hi @openedx/teaching-and-learning! Just following up on this!

Hi @openedx/teaching-and-learning - would someone be able to help with this?

**Review by connorhaugh — APPROVED** [review]

**Comment by mphilbrick211** [comment]
Hi @connorhaugh! Thanks so much for helping with review. Are you able to merge as well?

**Pull request merged**
