### PR TITLE
feat: allowing studio asides for course-authoring MFE

### PR DESCRIPTION
**Pull request by Anas12091101**
## Supporting Information
Issue: [Frontend App Course Authoring - Issue #545](https://github.com/openedx/frontend-app-course-authoring/issues/545)
EdX Platform PR: [EdX Platform - Pull Request #34026](https://github.com/openedx/edx-platform/pull/34026)

Note: This pull request should be reviewed concurrently with the EdX Platform PR.

## Description
The current problem editor page lacks options for configuring aside values of the problem xblock. This pull request addresses this by enabling the asides' studio views in the problem editor.

More information in the EdX Platform PR

Note: Styles are not finalized, and suggestions for improvement are welcome.

## Screenshot
Screenshot 2024-01-05 at 3 59 47 PM

## How to test locally
- In your local edx-platform, checkout to https://github.com/Anas12091101/edx-platform/tree/MFE-studio-view
- Login to edx-platform.
- In Studio, go to the edX Demo Course. Create a new unit which is a multiple choice problem.
- Configure the [rapid response aside](https://github.com/mitodl/rapid-response-xblock) for this problem.
- Add the [waffle flags](https://github.com/openedx/frontend-app-course-authoring?tab=readme-ov-file#requirements-1) to use the course authoring MFE in the studio admin if not already. 
- Click the edit tab on the problem xblock which will redirect you to the course authoring MFE if properly configured.
- You can see the rapid response aside being rendered in an iframe as shown in image above. 

(Note: The styling of the iframe has not been completed yet. The PR only offers a basic approach to resolve https://github.com/openedx/frontend-app-course-authoring/issues/545. It should be merged after the edx-platform PR is merged.)

### CODE REVIEW

**Comment by mphilbrick211** [comment]
Hi @Anas12091101! Thanks so much for this contribution! Please let me know if you have any questions on submitting a [CLA form](https://openedx.atlassian.net/wiki/spaces/COMM/pages/941457737/How+to+start+contributing+to+the+Open+edX+code+base). Thanks!

**Comment by pdpinch** [comment]
@mphilbrick211 Anas should be covered by the MIT Entity agreement. I don't know if you have access, but I've added him to the list at https://docs.google.com/spreadsheets/d/1HEaYDtoBtN-vvloA5UC-4oAHTVGzWbJWYVzYrEwFT4Y/edit#gid=755274227&range=28:28

**Comment by e0d** [comment]
I've added him.

**Comment by ali-hugo** [comment]
Hi @Anas12091101. I'd like to perform a product review on this PR, but I'm not a developer so don't know how to set up a dev environment. Would you mind uploading a screencast of the user flow for me to review? Thanks!

**Comment by pdpinch** [comment]
@Anas12091101 please add a section to the PR description with instructions on how to test this. It requires installing an xBlock that uses the asides functionality, right?

**Comment by Anas12091101** [comment]
> @Anas12091101 please add a section to the PR description with instructions on how to test this.

@pdpinch I was testing the functionality to create a screen cast and found some bugs in the functionality due to which the asides are not loading and throwing an error. I will write the testing instructions once I find the solution for this

**Comment by Anas12091101** [comment]
> Ok. I'm going to change this to "waiting on author" then.

I've fixed the problem in the edx-platform PR and have added the test steps in this PR's description

**Comment by bradenmacdonald** [comment]
@Anas12091101 @pdpinch is this PR still ready to go? We've now moved this code into https://github.com/openedx/frontend-app-course-authoring/ so we'll need you to please re-open this PR against https://github.com/openedx/frontend-app-course-authoring/ if you'd like to continue it. Feel free to reach out to me if you aren't sure how to do that using git and I can help (basically: add your local `content-components` repo as a remote in `course-authoring`, then pull the branch and rebase it).

**Comment by openedx-webhooks** [comment]
@Anas12091101 Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-lib-content-components&entry.867055334=https://github.com/openedx/frontend-lib-content-components/pull/452&entry.1484655318=https://github.com/Anas12091101&entry.752974735=2024-01-09+14:04&entry.1917517419=2024-08-29+19:09&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
